[package]
name = "memoize"
version = "0.1.0"
authors = ["Aurélien Ooms <aurelien.ooms@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.3.14"
sha-1 = "0.8.1"
dirs = "2.0.2"
